# Generated by Django 5.2.5 on 2025-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsl',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='newsl',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
